---
- name: Deploy Prometheus Node Exporter systemd service
  ansible.builtin.template:
    src: prometheus_node_exporter.service.j2
    dest: "/etc/systemd/system/{{ NODE_EXPORTER_SERVICE_NAME }}.service"
    owner: root
    group: root
    mode: "0644"
